name: Verify PR Labels
description: Verifies that the PR has the required labels

inputs:
  labels:
    required: true
    description: "The labels to verify"
  sha:
    description: "The commit SHA"
    required: true
  token:
    description: "The GitHub token to use for authentication"
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
