// Generated by ts-to-zod
import { z } from 'zod'

export const correlationIDSchema = z.number()

export const metadataSchema = z.object({
  created_at: z.string(),
  updated_at: z.string().optional(),
})

export const permissionSchema = z.string()

export const fieldValidationErrorSchema = z.object({
  field: z.string(),
  error: z.string(),
})

export const validationErrorSchema = z.object({
  fields: z.array(fieldValidationErrorSchema),
})
