// Code generated by tygo. DO NOT EDIT.

//////////
// source: api_token.go

export interface APITokenData {
  userId: UserID
  expiry: string /* ISO8601 */
  permissions: Array<Permission>
}
export interface APIToken extends APITokenData {
  id: APITokenID
  metadata?: Metadata
}
export interface APITokenWithSecret extends APIToken {
  secret: string
}

//////////
// source: api_token.ts.go

import { Metadata, Permission } from './domain.generated.ts'
import { UserID } from './user.generated.ts'

//////////
// source: api_token_id.go

export type APITokenID = number
