// Generated by ts-to-zod
import { z } from 'zod'

import { metadataSchema, permissionSchema } from './domain.generated.zod.ts'
import { userIDSchema } from './user.generated.zod.ts'

export const aPITokenDataSchema = z.object({
  userId: userIDSchema,
  expiry: z.string(),
  permissions: z.array(permissionSchema),
})

export const aPITokenIDSchema = z.number()

export const aPITokenSchema = aPITokenDataSchema.extend({
  id: aPITokenIDSchema,
  metadata: metadataSchema.optional(),
})

export const aPITokenWithSecretSchema = aPITokenSchema.extend({
  secret: z.string(),
})
