// Generated by ts-to-zod
import { z } from 'zod'

import { metadataSchema } from './domain.generated.zod.ts'
import { userIDSchema } from './user.generated.zod.ts'

export const chatSessionItemIDSchema = z.number()

export const chatSessionItemTypeSchema = z.union([
  z.literal('user'),
  z.literal('assistant'),
])

export const assistantChatSessionItemDataSchema = z.object({
  content: z.string(),
})

export const userChatSessionItemDataSchema = z.object({
  content: z.string().min(1),
  userId: userIDSchema,
})

export const chatSessionDataSchema = z.object({
  chatsessionitemids: z.array(chatSessionItemIDSchema),
  userids: z.array(z.unknown()),
})
