// Code generated by tygo. DO NOT EDIT.

//////////
// source: correlation_id.go

export type CorrelationID = number

//////////
// source: metadata.go

export interface Metadata {
  created_at: string /* ISO8601 */
  updated_at?: string /* ISO8601 */
}

//////////
// source: permissions.go

export type Permission = string
export const CustomerPermission: Permission = 'customer'
export const APIPermission: Permission = 'api'
export const AdminPermission: Permission = 'admin'

//////////
// source: validation.go

export interface ValidationError {
  fields: FieldValidationError[]
}
export interface FieldValidationError {
  field: string
  error: string
}
