// Generated by ts-to-zod
import { z } from 'zod'

import { metadataSchema } from './domain.generated.zod.ts'

export const rateLimitDataSchema = z.object({})

export const rateLimitIDSchema = z.number()

export const rateLimitSchema = rateLimitDataSchema.extend({
  id: rateLimitIDSchema,
  metadata: metadataSchema,
})
