// Code generated by tygo. DO NOT EDIT.

//////////
// source: rate_limit.go

export interface RateLimitData {}
export interface RateLimit extends RateLimitData {
  id: RateLimitID
  metadata: Metadata
}

//////////
// source: rate_limit.ts.go

import { Metadata } from './domain.generated.ts'

//////////
// source: rate_limit_id.go

export type RateLimitID = number
