// Generated by ts-to-zod
import { z } from 'zod'

import { metadataSchema } from './domain.generated.zod.ts'

export const secretTypeSchema = z.union([
  z.literal('environment'),
  z.literal('stored'),
])

export const secretIDSchema = z.number()

export const environmentSecretDataSchema = z.object({
  name: z.string().min(1),
})

export const secretBaseSchema = z.object({
  id: secretIDSchema,
  type: secretTypeSchema,
  metadata: metadataSchema.optional(),
})

export const storedSecretDataSchema = z.object({
  salt: z.string(),
  value: z.string(),
})

export const storedSecretSchema = secretBaseSchema
  .extend(storedSecretDataSchema.shape)
  .extend({
    type: z.literal('stored'),
  })

export const environmentSecretSchema = secretBaseSchema
  .extend(environmentSecretDataSchema.shape)
  .extend({
    type: z.literal('environment'),
  })

export const secretSchema = z.union([
  environmentSecretSchema,
  storedSecretSchema,
])
