// Code generated by tygo. DO NOT EDIT.

//////////
// source: secret.ts.go

import { Metadata } from './domain.generated.ts'

export type SecretType = 'environment' | 'stored'

export type Secret = EnvironmentSecret | StoredSecret

//////////
// source: secret_base.go

export interface SecretBase {
  id: SecretID
  type: SecretType

  metadata?: Metadata
}

//////////
// source: secret_environment.go

export interface EnvironmentSecretData {
  /**
   * 	 @minLength 1
   */
  name: string
}
export interface EnvironmentSecret extends SecretBase, EnvironmentSecretData {
  type: 'environment'
}

//////////
// source: secret_id.go

export type SecretID = number

//////////
// source: secret_stored.go

export interface StoredSecretData {
  salt: string
  value: string
}
export interface StoredSecret extends SecretBase, StoredSecretData {
  type: 'stored'
}
