// Code generated by tygo. DO NOT EDIT.

//////////
// source: task_id.go

export type TaskID = number

//////////
// source: task_result.ts.go

type TaskResultID = number & { taskResultID: true }

export type TaskResultType = 'success' | 'failure'

export type TaskResult = TaskResultSuccess | TaskResultFailure

//////////
// source: task_result_failure.go

export interface TaskResultFailureData {
  error: string
}
export interface TaskResultFailure
  extends TaskResultBase,
    TaskResultFailureData {
  type: 'failure'
}

//////////
// source: task_results_base.go

export interface TaskResultBase {
  id: TaskResultID
  type: TaskResultType

  task_id: TaskID
  metadata?: unknown /* domain.Metadata */
}

//////////
// source: task_results_success.go

export interface TaskResultSuccessData {
  result: unknown /* json.RawMessage */
}
export interface TaskResultSuccess
  extends TaskResultBase,
    TaskResultSuccessData {
  type: 'success'
}

//////////
// source: tasks.ts.go

import { ChatSessionItem } from './chatsession.generated.ts'
import { User, UserData, UserID } from './user.generated.ts'
import { APIToken, APITokenData, APITokenID } from './apitoken.generated.ts'
import { Secret, SecretID } from './secret.generated.ts'

export type TaskType =
  | 'create_token'
  | 'create_token_with_id'
  | 'get_token'
  | 'delete_token'
  | 'answer_question'
  | 'get_secret'
  | 'create_secret'
  | 'create_secret_with_id'
  | 'update_secret'
  | 'delete_secret'
  | 'create_user'
  | 'create_user_with_id'
  | 'update_user'
  | 'get_user'
  | 'delete_user'
  | 'answer_question'

export type TaskStatus = 'not_started' | 'running' | 'completed' | 'failed'

export type Task =
  | CreateUserTask
  | CreateUserWithIdTask
  | UpdateUserTask
  | GetUserTask
  | DeleteUserTask
  | GetSecretTask
  | CreateSecretTask
  | CreateSecretWithIdTask
  | UpdateSecretTask
  | DeleteSecretTask
  | CreateTokenTask
  | CreateTokenWithIdTask
  | GetTokenTask
  | DeleteTokenTask
  | AnswerQuestionTask

//////////
// source: tasks_api_token.go

export interface CreateTokenTaskData {
  user_id: UserID
  data: APITokenData
}
export interface CreateTokenTask extends TaskBase, CreateTokenTaskData {
  type: 'create_token'
}
export interface CreateTokenWithIdTaskData {
  user_id: UserID
  api_token_id: APITokenID
  data: APITokenData
}
export interface CreateTokenWithIdTask
  extends TaskBase,
    CreateTokenWithIdTaskData {
  type: 'create_token_with_id'
}
export interface GetTokenTaskData {
  user_id: UserID
  token_id: APITokenID
}
export interface GetTokenTask extends TaskBase, GetTokenTaskData {
  type: 'get_token'
}
export interface DeleteTokenTaskData {
  user_id: UserID
  token_id: APITokenID
}
export interface DeleteTokenTask extends TaskBase, DeleteTokenTaskData {
  type: 'delete_token'
}

//////////
// source: tasks_base.go

export interface TaskBase {
  id: TaskID
  type: TaskType

  status: TaskStatus
  metadata?: unknown /* domain.Metadata */
}

//////////
// source: tasks_chat_sessions.go

export interface AnswerQuestionTaskData {
  user_id: UserID
  items: Array<ChatSessionItem>
}
export interface AnswerQuestionTask extends TaskBase, AnswerQuestionTaskData {
  type: 'answer_question'
}

//////////
// source: tasks_secrets.go

export interface GetSecretTaskData {
  secret_id: SecretID
}
export interface GetSecretTask extends TaskBase, GetSecretTaskData {
  type: 'get_secret'
}
export interface CreateSecretTaskData {
  user_id: UserID
  value: string
}
export interface CreateSecretTask extends TaskBase, CreateSecretTaskData {
  type: 'create_secret'
}
export interface CreateSecretWithIdTaskData {
  user_id: UserID
  secret_id: SecretID
  value: string
}
export interface CreateSecretWithIdTask
  extends TaskBase,
    CreateSecretWithIdTaskData {
  type: 'create_secret_with_id'
}
export interface UpdateSecretTaskData {
  user_id: UserID
  secret_id: SecretID
  value: string
}
export interface UpdateSecretTask extends TaskBase, UpdateSecretTaskData {
  type: 'update_secret'
}
export interface DeleteSecretTaskData {
  user_id: UserID
  secret_id: SecretID
}
export interface DeleteSecretTask extends TaskBase, DeleteSecretTaskData {
  type: 'delete_secret'
}

//////////
// source: tasks_users.go

export interface CreateUserTaskData {
  user_data: UserData
}
export interface CreateUserTask extends TaskBase, CreateUserTaskData {
  type: 'create_user'
}
export interface CreateUserWithIdTaskData {
  user_id: UserID
  user_data: UserData
}
export interface CreateUserWithIdTask
  extends TaskBase,
    CreateUserWithIdTaskData {
  type: 'create_user_with_id'
}
export interface UpdateUserTaskData {
  user?: User
}
export interface UpdateUserTask extends TaskBase, UpdateUserTaskData {
  type: 'update_user'
}
export interface GetUserTaskData {
  user_id: UserID
}
export interface GetUserTask extends TaskBase, GetUserTaskData {
  type: 'get_user'
}
export interface DeleteUserTaskData {
  user_id: UserID
}
export interface DeleteUserTask extends TaskBase, DeleteUserTaskData {
  type: 'delete_user'
}
