// Code generated by tygo. DO NOT EDIT.

//////////
// source: user.go

export interface User extends UserData {
  id: UserID
  metadata?: Metadata
}
export interface UserData {
  /**
   * 	   @format email
   */
  email?: string
  /**
   * 	   @minLength 1
   */
  first_name?: string
  /**
   * 	   @minLength 1
   */
  last_name?: string
}

//////////
// source: user.ts.go

import { Metadata } from './domain.generated.ts'

//////////
// source: user_id.go

export type UserID = number
