// Generated by ts-to-zod
import { z } from 'zod'

import { metadataSchema } from './domain.generated.zod.ts'

export const userDataSchema = z.object({
  email: z.string().email().optional(),
  first_name: z.string().min(1).optional(),
  last_name: z.string().min(1).optional(),
})

export const userIDSchema = z.number()

export const userSchema = userDataSchema.extend({
  id: userIDSchema,
  metadata: metadataSchema.optional(),
})
