// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ApiToken struct {
	ID        int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Data      json.RawMessage
}

type Card struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Type      string
	Data      json.RawMessage
}

type ChatSession struct {
	ID        int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Data      json.RawMessage
}

type ChatSessionItem struct {
	ID        int64
	UserID    int64
	SessionID int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Type      string
	Data      json.RawMessage
}

type Deck struct {
	ID        int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Data      json.RawMessage
}

type GameState struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Data      json.RawMessage
}

type GameStateVersion struct {
	ID          int64
	GameStateID int64
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	Data        json.RawMessage
}

type Integration struct {
	ID        int64
	Type      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Data      json.RawMessage
}

type RateLimit struct {
	ID        int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Data      json.RawMessage
}

type Secret struct {
	ID        int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Data      json.RawMessage
}

type User struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Data      json.RawMessage
}
