name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Go Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Test
        run: |
          curl https://gotest-release.s3.amazonaws.com/gotest_linux > gotest
          chmod +x gotest
          sudo mv gotest /usr/local/bin/
          make test
        env:
          DOCKER_HOST: tcp://docker:2375
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          DOCKER_BUILDKIT: 1
