name: Verify PR Checklist

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: number
        description: "The issue/PR number"

permissions:
  pull-requests: write
  contents: read
  checks: write
  issues: read

jobs:
  verify-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Acknowledgements
        uses: actions/github-script@v6
        env:
          ISSUE_NUMBER: ${{ inputs.issue_number }}

        with:
          script: |
            const verifyChecklist = require('./.github/workflows/scripts/verify-checklist.js');
            await verifyChecklist({ github, context }, process.env.ISSUE_NUMBER);
