name: Check PR Checklist

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  checks: write

jobs:
  check-boxes:
    runs-on: ubuntu-latest
    steps:
      - name: Check Acknowledgements
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.event_name === 'pull_request' ? context.payload.pull_request.number : context.issue.number
            });
            
            const checklistComment = response.data.find(comment => 
              comment.body.includes('## Required Acknowledgements')
            );
            
            if (!checklistComment) {
              return;
            }
            
            const uncheckedBoxes = (checklistComment.body.match(/\[ \]/g) || []).length;
            if (uncheckedBoxes > 0) {
              core.setFailed(`Error: ${uncheckedBoxes} unchecked boxes found in PR checklist`);
            }
