name: PR Label Check

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

env:
  REQUIRED_LABELS: '["feature", "bug"]'

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required labels
        uses: actions/github-script@v6
        with:
          script: |
            const requiredLabels = JSON.parse(process.env.REQUIRED_LABELS);
            const prLabels = context.payload.pull_request.labels.map(label => 
              label.name.toLowerCase()
            );
            
            const hasRequiredLabel = requiredLabels.some(required => 
              prLabels.includes(required.toLowerCase())
            );
            
            if (!hasRequiredLabel) {
              core.setFailed(`PR must have one of these labels: ${requiredLabels.join(', ')}`);
            }
