name: Verify PR Checklist

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: number
        description: "The issue/PR number"

permissions:
  pull-requests: write
  contents: read
  checks: write
  issues: read

jobs:
  verify-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Acknowledgements
        env:
          ISSUE_NUMBER: ${{ inputs.issue_number }}
        uses: ./.github/scripts/verify-checklist.js
