name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write 
  contents: read
  checks: write
  issues: write
  actions: write

jobs:
  build-actions:
    name: Build Actions
    uses: ./.github/workflows/build-actions.yml
    secrets: inherit

  setup-go:
    name: Setup Go
    uses: ./.github/workflows/setup-go.yml
    secrets: inherit

  verify-labels:
    name: Verify PR Labels
    needs: [build-actions]
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/verify-labels.yml
  
  verify-description:
    name: Verify PR Description
    needs: [build-actions]
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/verify-description.yml
    with:
      pr_body: ${{ github.event.pull_request.body }}
      sha: ${{ github.sha }}

  verify-checklist:
    name: Verify PR Checklist
    needs: [build-actions]
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request) }}
    uses: ./.github/workflows/verify-checklist.yml
    with:
      issue_number: ${{ github.event.pull_request.number || github.event.issue.number }}
    secrets: inherit

  create-checklist:
    name: Create PR Checklist
    needs: [build-actions]
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened') }}
    uses: ./.github/workflows/create-checklist.yml
    with:
      issue_number: ${{ github.event.pull_request.number }}

  build-backend:
    name: Build Backend
    needs: [setup-go]
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'opened') }}
    uses: ./.github/workflows/build-backend.yml
    with:
      cache-key: ${{ needs.setup-go.outputs.cache-key }}

  lint-backend:
    name: Lint Backend
    needs: [setup-go]
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'opened') }}
    uses: ./.github/workflows/lint-backend.yml
    with:
      cache-key: ${{ needs.setup-go.outputs.cache-key }}

  test-backend:
    name: Test Backend
    needs: [setup-go]
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'opened') }}
    uses: ./.github/workflows/test-backend.yml
    with:
      cache-key: ${{ needs.setup-go.outputs.cache-key }}

concurrency:
  group: ci
  cancel-in-progress: true
