name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write 
  contents: read
  checks: write
  issues: write
  actions: write

jobs:
  build-actions:
    name: Build Actions
    uses: ./.github/workflows/build-actions.yml

  setup-go:
    name: Setup Go
    uses: ./.github/workflows/setup-go.yml
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'opened') }}
    secrets: inherit

  create-checklist:
    name: Create PR Checklist
    needs: [build-actions]
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened') }}
    uses: ./.github/workflows/create-checklist.yml
    with:
      issue_number: ${{ github.event.pull_request.number }}
    secrets: inherit

  build-backend:
    name: Build Backend
    needs: [setup-go]
    uses: ./.github/workflows/go-template-workflow.yml
    with:
      cache-key: ${{ needs.setup-go.outputs.cache-key }}
      action-name: "Build"
      command: "make build"

  lint-backend:
    name: Lint Backend
    needs: [setup-go]
    uses: ./.github/workflows/go-template-workflow.yml
    with:
      cache-key: ${{ needs.setup-go.outputs.cache-key }}
      action-name: "Lint"
      command: "make lint"

  test-backend:
    name: Test Backend
    needs: [setup-go]
    uses: ./.github/workflows/go-template-workflow.yml
    with:
      cache-key: ${{ needs.setup-go.outputs.cache-key }}
      action-name: "Test"
      command: "go test ./..."

  verify-checklist:
    name: Verify PR Checklist
    needs: [build-actions]
    uses: ./.github/workflows/verify-checklist.yml
    with:
      issue_number: ${{ github.event.pull_request.number || github.event.issue.number }}
    secrets: inherit
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request) }}

  verify-description:
    name: Verify PR Description
    needs: [build-actions]
    uses: ./.github/workflows/verify-description.yml
    with:
      pr_body: ${{ github.event.pull_request.body }}
      sha: ${{ github.sha }}
    secrets: inherit
    if: ${{ github.event_name == 'pull_request' }}

  verify-labels:
    name: Verify PR Labels
    needs: [build-actions]
    uses: ./.github/workflows/pr-validation-template-workflow.yml
    with:
      action: ./.github/actions/verify-labels/
      labels: ${{ toJson(github.event.pull_request.labels.*.name) }}
      sha: ${{ github.sha }}
    secrets: inherit
    if: ${{ github.event_name == 'pull_request' }}
  
concurrency:
  group: ci
  cancel-in-progress: true
