name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
  issue_comment:
    types: [created, edited]
  push:

permissions:
  pull-requests: write 
  contents: read
  checks: write

jobs:
  check-pr-labels:
    name: Check PR Labels
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/check-pr-labels.yml
  
  check-pr-description:
    name: Check PR Description
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/check-pr-description.yml
    with:
      pr_body: ${{ github.event.pull_request.body }}
      sha: ${{ github.sha }}

  check-pr-checklist:
    name: Check PR Checklist
    if: ${{ github.event_name == 'issue_comment' || github.event_name == 'pull_request' }}
    uses: ./.github/workflows/check-pr-checklist.yml
    with:
      issue_number: ${{ github.event.pull_request.number || github.event.issue.number }}

  build-and-test:
    if: ${{ github.event_name == 'push' }}
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml

