name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  issue_comment:
    types: [created, edited]
  push:

permissions:
  pull-requests: write 
  contents: read
  checks: write

jobs:
  check-pr-labels:
    name: Check PR Labels
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    uses: ./.github/workflows/check-pr-labels.yml
  
  check-pr-description:
    name: Check PR Description
    if: github.event_name == 'pull_request' && ['opened', 'edited', 'reopened', 'synchronize'].includes(github.event.action)
    uses: ./.github/workflows/check-pr-description.yml

  check-pr-checklist:
    name: Check PR Checklist
    if: (github.event_name == 'pull_request' && ['opened', 'edited', 'reopened', 'synchronize'].includes(github.event.action)) || (github.event_name == 'issue_comment' && github.event.action == 'edited')
    uses: ./.github/workflows/check-pr-checklist.yml

  build-and-test:
    name: Build and Test
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-and-test.yml
