on:
  workflow_call:
    inputs:
      action-name:
        description: "Name of the action"
        required: true
        type: string
      cache-key:
        description: "Cache key for Go dependencies"
        required: true
        type: string
      command:
        description: "Command to run"
        required: true
        type: string
      sha:
        description: "The commit SHA"
        required: true
        type: string

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  go-template-workflow:
    name: ${{ inputs.action-name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Built Actions
        uses: actions/download-artifact@v4
        with:
          name: actions
          path: .github/actions

      - name: Create Status
        uses: ./.github/actions/create-status/
        id: status
        with:
          name: '${{ inputs.action-name }} Verification'
          sha: ${{ inputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Clear Go directories
        run: |
          sudo chmod -R 777 ~/go/pkg/mod || true
          rm -rf ~/go/pkg/mod
          rm -rf ~/.cache/go-build

      - name: Use Go Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ inputs.cache-key }}

      - name: Run Action
        id: action
        run: ${{ inputs.command }}
        continue-on-error: true

      - name: Update Status
        uses: ./.github/actions/update-status/
        with:
          check_id: ${{ steps.status.outputs.check_id }}
          outcome: ${{ steps.action.outcome }}
          token: ${{ secrets.GITHUB_TOKEN }}
