on:
  workflow_call:
    inputs:
      cache-key:
        description: "Cache key for Go dependencies"
        required: true
        type: string

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Create Lint Status
        uses: actions/github-script@v6
        with:
          script: |
            const check = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Lint Verification',
              head_sha: context.sha,
              status: 'in_progress'
            });
            core.exportVariable('LINT_CHECK_ID', check.data.id);

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Use Go Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ inputs.cache-key }}

      - name: Lint
        id: lint
        run: make lint
        continue-on-error: true

      - name: Update Lint Status
        uses: actions/github-script@v6
        with:
          script: |
            const conclusion = '${{ steps.lint.outcome }}' === 'success' ? 'success' : 'failure';
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: process.env.LINT_CHECK_ID,
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: 'Lint Verification',
                summary: conclusion === 'success' ? 'Linting completed successfully' : 'Linting failed'
              }
            });

