on:
  workflow_call:
    outputs:
      cache-key:
        description: "Cache key for Go dependencies"
        value: ${{ jobs.setup-go.outputs.cache-key }}

permissions:
  contents: read
  actions: write

jobs:
  setup-go:
    name: Setup Go
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Go Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

