on:
  workflow_call:
    inputs:
      cache-key:
        description: "Cache key for Go dependencies"
        required: true
        type: string

permissions:
  contents: read
  checks: write

jobs:
  test-backend:
    uses: ./.github/workflows/go-template-workflow.yml
    with:
      cache-key: ${{ inputs.cache-key }}
      action-name: "Test"
      command: "go test ./..."
