on: 
  workflow_call:
    inputs:
      labels:
        required: true
        type: string
        description: "The labels to verify"
      sha:
        required: true
        type: string
        description: "The commit SHA"

permissions:
  pull-requests: read
  contents: read
  checks: write

jobs:
  verify-labels:
    name: Verify Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Built Actions
        uses: actions/download-artifact@v4
        with:
          name: actions
          path: .github/actions

      - name: Verify Labels
        uses: ./.github/actions/verify-labels/
        with:
          labels: ${{ inputs.labels }}
          sha: ${{ inputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

